add NOTICE file and extend the LICENSE file
kadai-io/kadai pull request #18
Opened 2024-09-06 14:39 UTC by ryzheboka

### Thanks for your PR! Please fill out the following list :)

---

- [ ] I put the ticket or multiple tickets in review
- [ ] Commit message format → Closes #&lt;Issue Number&gt; - Your commit message.
- [ ] Sonarcloud link : \<add the link here>
- [x] No documentation update needed
- [ ] Link to PR with documentation update: \<add the link here>
- [x] No Release Notes needed
- [ ] Release Notes :

```

```

2024-09-09 07:41 UTC, CRoberto1926 commented on LICENSE
> +Licenses used by KADAI dependencies:
I would group the licenses and sort them alphabetically, in such a way that each license only once appears, and then there's a list of packages that use this license.

2024-09-09 07:41 UTC, CRoberto1926 commented on LICENSE
> + (The Apache Software License, Version 2.0) Jackson-core (com.fasterxml.jackson.core:jackson-core:2.15.3 - https://github.com/FasterXML/jackson-core)
We can probably condense this in a single line, if we ignore the version of the artifact. There are many occurrences of this.

2024-09-09 07:41 UTC, CRoberto1926 commented on LICENSE
> + (The Apache Software License, Version 2.0) Jackson-module-parameter-names (com.fasterxml.jackson.module:jackson-module-parameter-names:2.15.3 - https://github.com/FasterXML/jackson-modules-java8/jac
I am also not sure if we need to be this precise or just say FasterXML/Jackson. For another example see the docker artifacts lines just below. There are many occurrences of this.

2024-09-09 07:41 UTC, CRoberto1926 commented on NOTICE
> +The list also contains files introduced to KADAI that are not part of TASKANA.
How is this list generated? Should we include the generation in the CI?

2024-09-09 07:41 UTC, CRoberto1926 commented on README.md
>  and [envite consulting GmbH](https://envite.de/) with the support of the open source community.
Sorry I don't understand this sentence :)

"is being developed by envite consulting GmbH and envite consulting GmbH" ???

Isn't it enough "is being developed by envite consulting GmbH with the support of the open source community"?

2024-09-09 09:39 UTC, holgerhagen requested changes
Istn't the LICENSE file meant to contain the Apache 2.0 Licence itself?

2024-09-10 08:24 UTC, ryzheboka commented on LICENSE
> +Licenses used by KADAI dependencies:
That's a great idea! Firefox also does it this way

2024-09-10 08:27 UTC, ryzheboka commented on NOTICE
> +The list also contains files introduced to KADAI that are not part of TASKANA.
It is generated with mvn license:third-party-report. However, the command is not executed quite right, because some modules throw exceptions. The generation of the list is also flawed, because it has some dependieces multiple times depending on the artifact, as you commented above

2024-09-10 08:27 UTC, ryzheboka commented on README.md
>  and [envite consulting GmbH](https://envite.de/) with the support of the open source community.
That was a copy paste error :) I will delete this

2024-09-10 08:33 UTC, ryzheboka commented
> Istn't the LICENSE file meant to contain the Apache 2.0 Licence itself?

In the [guide to the LICENSE and NOTICE files](https://infra.apache.org/licensing-howto.html) for an Apache 2.0 project, it says:
"
In LICENSE, add a pointer to the dependency's license within the distribution and a short note summarizing its licensing:

_This product bundles SuperWidget 1.2.3, which is available under a
"3-clause BSD" license. For details, see deps/superwidget/."_
"

2024-09-10 08:35 UTC, ryzheboka commented on LICENSE
> + (Apache License, Version 2.0) Spring Auto REST Docs Annotations (capital.scalable:spring-auto-restdocs-annotations:2.0.11 - https://github.com/scacap/spring-auto-restdocs/spring-auto-restdocs-annota
I generated the list in june, that's why the dependency is still there. Do you know which dependencies we deleted since then? Generating the list is sadly not very straight forward, esp. right now, but I can try to generate it again

2024-09-18 07:33 UTC, merged