Rename to Kadai
kadai-io/kadai pull request #7
Opened 2024-08-20 09:02 UTC by jamesrdi

### Thanks for your PR! Please fill out the following list :)

---
- [ ] I put the ticket or multiple tickets in review
- [ ] Commit message format → Closes #&lt;Issue Number&gt; - Your commit message.
- [ ] Sonarcloud link : \<add the link here>
- [ ] No documentation update needed
- [ ] Link to PR with documentation update: \<add the link here>
- [ ] No Release Notes needed
- [ ] Release Notes :

```

```

2024-08-21 08:08 UTC, jamesrdi commented
TASKANA logo in the UI still has to be replaced.

I replaced the azure links with e.g https://kadai.azurewebsites.net/kadai, even though we still have not deployed to Azure yet

2024-08-21 12:03 UTC, ryzheboka requested changes

2024-08-21 12:03 UTC, ryzheboka commented on history/kadai-loghistory-provider/src/main/resources/META-INF/services/pro.kadai.spi.history.api.KadaiHistory
Please rename pro.kadai to io.kadai everywhere

2024-08-21 13:49 UTC, jamesrdi commented on .run/Build Backend No Checkstyle.run.xml
> -              <option value="-Dasciidoctor.skip" />
Because that is only relevant for generating RestDoc, which we do not use anymore

2024-08-21 13:49 UTC, jamesrdi commented on .run/Build Backend.run.xml
> -              <option value="-Dasciidoctor.skip" />
Same as above

2024-08-23 07:59 UTC, ryzheboka commented on .run/Build Backend No Checkstyle.run.xml
> -              <option value="-Dasciidoctor.skip" />
Why in this PR?

2024-08-23 08:04 UTC, jamesrdi commented on .run/Build Backend No Checkstyle.run.xml
> -              <option value="-Dasciidoctor.skip" />
I missed it in the last PR. Should I open a new PR for this?

2024-08-23 10:02 UTC, merged