Closes #47 - Fix flakiness of some tests
kadai-io/kadai pull request #99
Opened 2024-10-28 13:32 UTC by CRoberto1926

### Thanks for your PR! Please fill out the following list :)

---

- [x] I put the ticket or multiple tickets in review
- [x] Commit message format → Closes #&lt;Issue Number&gt; - Your commit message.
- [ ] Sonarcloud link : \<add the link here>
- [x] No documentation update needed
- [ ] Link to PR with documentation update: \<add the link here>
- [x] No Release Notes needed
- [ ] Release Notes :

```

```

2024-10-29 14:37 UTC, ryzheboka requested changes

2024-10-29 14:37 UTC, ryzheboka commented on lib/kadai-core-test/src/test/java/acceptance/jobs/AbstractKadaiJobAccTest.java
> +
Why did you add an empty line here?

2024-10-29 14:37 UTC, ryzheboka commented on lib/kadai-core/src/test/java/acceptance/task/ServiceLevelPriorityWithWorkingDaysCalculationAccTest.java
> +    if (!localDateNow.isEqual(localDateInTwoHours)
Do you think it's better to work with a fixed date instead of now? This way, we won't need to check if now lies between 22:00:00 and 23:59:59 of a working day that precedes a non working day

2024-10-30 06:00 UTC, CRoberto1926 commented on lib/kadai-core-test/src/test/java/acceptance/jobs/AbstractKadaiJobAccTest.java
> +
There isn't a particular reason, sometimes I find more readable to have an empty line between the method declaration and the first line of code in the method. Do you want me to delete this empty line?

2024-10-30 06:05 UTC, CRoberto1926 commented on lib/kadai-core/src/test/java/acceptance/task/ServiceLevelPriorityWithWorkingDaysCalculationAccTest.java
> +    if (!localDateNow.isEqual(localDateInTwoHours)
Yes, that was also my first idea. Unfortunately, the TaskService.createTask() method sets the created property of a task to the Instant in which the task is created, so we would need to modify that code (see TaskServiceImpl.standardSettingsOnTaskCreation()).

2024-10-30 06:05 UTC, CRoberto1926 commented on lib/kadai-core/src/test/java/acceptance/task/ServiceLevelPriorityWithWorkingDaysCalculationAccTest.java
> +    if (!localDateNow.isEqual(localDateInTwoHours)
I guess that we don't want to modify TaskServiceImpl for this test...

2024-11-08 08:55 UTC, ryzheboka commented on lib/kadai-core-test/src/test/java/acceptance/jobs/AbstractKadaiJobAccTest.java
> +
Yes

2024-11-08 08:56 UTC, ryzheboka commented on lib/kadai-core/src/test/java/acceptance/task/ServiceLevelPriorityWithWorkingDaysCalculationAccTest.java
> +    if (!localDateNow.isEqual(localDateInTwoHours)
We definitly don't want to mondify productive code for a test. Could you use TaskImpl.setCreated method in the test after creation?

2024-11-11 13:32 UTC, CRoberto1926 commented on lib/kadai-core-test/src/test/java/acceptance/jobs/AbstractKadaiJobAccTest.java
> +
done

2024-11-11 13:37 UTC, CRoberto1926 commented on lib/kadai-core/src/test/java/acceptance/task/ServiceLevelPriorityWithWorkingDaysCalculationAccTest.java
> +    if (!localDateNow.isEqual(localDateInTwoHours)
Yes, we could. But what would be the advantage to it? Isn't it the same as skipping the assertion?

2024-11-13 09:31 UTC, ryzheboka approved these changes

2024-11-13 09:32 UTC, merged